name: "CI Build"

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/gradle-build-action@v2.7.1
      - run: "./oj check"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  test-functional:
    needs: check
    strategy:
      matrix:
        module: [app-javafx, lib]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/gradle-build-action@v2.7.1
      - run: "./oj :${{ matrix.module }}:checkFunctional"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  package:
    needs: check
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/gradle-build-action@v2.7.1
      - run: "./oj assemble${{ matrix.os }}"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}

  build:
    needs: [test-functional, package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version-file: .oj/jdk-version.txt
      - uses: gradle/gradle-build-action@v2.7.1
      - run: "./oj build"
        env:
          BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
          BUILD_CACHE_PWD: ${{ secrets.BUILD_CACHE_PWD }}
      - uses: actions/upload-artifact@v4.0.0
        with:
          name: Application Packages
          path: .oj/build/*/packages/*